### PR TITLE
Create pt-br.json

### PR DESCRIPTION
**Pull request by JoseLuizFranco**
🇧🇷 | Brazilian portugues translation

### CODE REVIEW

**Comment by theRealPadster** [comment]
When I test Brazilian portugues, this is what I get for `searchPageShelfAriaLabel`. Is it the same for you? 
image

**Comment by JoseLuizFranco** [comment]
Yeah, I misunderstood the meaning - context would be actually necessary this time 😅. It should be just like the img.
"Navegar por todas as seções"

**Comment by theRealPadster** [comment]
> Yeah, I misunderstood the meaning - context would be actually necessary this time 😅. It should be just like the img. "Navegar por todas as seções"

Ah, okay. I opened a new issue. Feel free to submit another PR or I can do it when I get a chance.

**Comment by theRealPadster** [comment]
Translation updated.

**Pull request merged**
