### PR TITLE
Support German locale

### PR DESCRIPTION
**Pull request by D3SOX**
Not sure why the locales are also in the root of the project, I only added it to `src` as mentioned in the release notes

### CODE REVIEW

**Comment by theRealPadster** [comment]
I don't see any in the root. Thanks, will add :)

**Comment by theRealPadster** [comment]
It should be enabled now if you download the lastest `hidePodcasts.js` from the main branch.

**Comment by theRealPadster** [comment]
Oh, I see what you mean. For some reason there was a locale folder in `/` and one in `src`. Idk why it was there. Removed. Thanks.

**Comment by D3SOX** [comment]
It looks like it's not applied properly

image

**Comment by D3SOX** [comment]
Forgot that a `git pull` is not enough, thx

**Pull request merged**
